sudo: required
language: java
jdk:
   - oraclejdk8
   - oraclejdk11
services:
   - docker
env:
   global:
      - REGISTRY_USER=taoudi
      - REGISTRY_PASS=whatever
      - secret: 12345678910
script:
   - docker build -t app .
   - docker run -p 8080:8080 -t app
after_script:
   - docker images
before_deploy:
   - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
   provider: script
   script: docker push kthboyz/fairgrounds:app
