sudo: required
language: java
jdk:
   - oraclejdk8
services:
   - docker
env:
   global:
      - REGISTRY_USER=taoudi
      - REGISTRY_PASS=whatever
      - secret: 12345678910
before-script:
   - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
script:
   #- ./mvnw clean install -B
   - docker build -t app .
after_script:
   - docker images
   - docker tag local-image:app kthboyz/fairgrounds:app
   - docker push kthboyz/fairgrounds:app