sudo: required
language: java
jdk:
   - oraclejdk8
services:
   - docker
env:
   global:
      - REGISTRY_USER=taoudi
      - REGISTRY_PASS=whatever
      - secret: 12345678910
script:
   #- ./mvnw clean install -B
   - docker build -t fairgrounds .
after_script:
   - docker images
before_deploy:
   - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
   - docker tag fairgrounds kthboyz/fairgrounds:fairgrounds
   - docker push kthboyz/fairgrounds:fairgrounds
deploy:
   provider: heroku
   api_key:
      secure: b1914aef-2241-4c05-988c-68866367fdd8
   app: kthboyz-fairgrounds
   on:
      repo: kth-boyz/FairGrounds
      branch: test