language: java
jdk:
   - oraclejdk8
   - oraclejdk11
addons:
   - mysql: '14.14'
#env:
#   global:
#      - MYSQL_PORT_3306_TCP_ADDR=localhost
#      - MYSQL_PORT_3306_TCP_PORT=3306
services:
   - docker
before_install:
#   - docker pull carlad/sinatra
   - docker build -t app .;
   - docker run -p 8080:8080 -t app
after_script:
   - docker images
   - echo "Current directory is $(pwd)"
   - ls
   - cat target/site/pmd/cpd.xml
   - cat target/site/pmd/pmd.xml
   - cat target/site/findbugs/findbugsXml.xml