sudo: required
language: java
jdk:
   - oraclejdk8
services:
   - docker
env:
   global:
      - REGISTRY_USER=taoudi
      - REGISTRY_PASS=whatever
      - secret: 12345678910
script:
   - docker build -t fairgrounds .
after_script:
   - docker images
before_deploy:
   - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
   - docker tag fairgrounds kthboyz/fairgrounds:fairgrounds
   - docker push kthboyz/fairgrounds:fairgrounds
deploy:
   provider: heroku
   api_key:
      secure: 6ecada15-2e15-4b3d-9652-1c520c306f17
   app: kthboyz-fairgrounds
   on:
      repo: kth-boyz/FairGrounds
      branch: master
