sudo: required
language: java
jdk:
   - oraclejdk8
services:
   - docker
env:
   global:
      - REGISTRY_USER=taoudi
      - REGISTRY_PASS=whatever
      - secret: 12345678910
script:
   #- ./mvnw clean install -B
   - docker build -t fairgrounds .
after_script:
   - docker images
   - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
   - docker tag app kthboyz/fairgrounds
   - docker push kthboyz/fairgrounds