sudo: required
language: java
jdk:
   - oraclejdk8
services:
   - docker
env:
   global:
      - REGISTRY_USER=taoudi
      - REGISTRY_PASS=whatever
      - secret: 12345678910
script:
   #- ./mvnw clean install -B
   - docker build -t fairgrounds .
after_script:
   - docker images


before_deploy:
   - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
   - docker tag fairgrounds kthboyz/fairgrounds:fairgrounds
deploy:
   provider: script
   script: docker run -p 8080:8080 -t fairgrounds
   on:
      branch: test